config/routes.rb
Plmt::Application.routes.draw do
  resources :owners

  resources :elilists

  resources :panlists do
    member do
      get 'migrate' 
    end
  end

  root to: 'migrations#dashboard'
  match '/dashboard', to: 'migrations#dashboard'
  match '/dashboard/:netid', to: 'migrations#dashboard' 

end

app/models/elilist.rb
require 'gappsprovisioning/provisioningapi.rb'

class Elilist < ActiveRecord::Base
  include GAppsProvisioning
  attr_accessible :list_type, :name, :list_id, :description, :owners_raw, :subscribers_raw
  # attr_accessor :owners, :subscribers

  def google_group_type
    return case list_type
      when 'Announcement' then 'Owner'
      when 'Moderated' then 'Member'
      when 'Discussion' then 'Anyone'
      else 'Owner'
      end
  end
  def google_group_id
    val = self.list_id || self.name || ""
    # dasherize the id
    val.gsub /\s+/, "-"
  end

  def create_google_group
    self.google_group_create
    subscribers.each do |subscriber| 
      self.google_group_add_member subscriber
    end
=begin
    group = google.create_group self.google_group_id, [name, 'just a description', group_type]
    owners_arr.each do |owner| 
      google.add_member_to_group owner, group_id # make sure is a member before is an owner
      google.add_owner_to_group owner, group_id
    end
=end
  end

  def owners
    self.owners_raw.split
  end
  def owners= o
    self.owners_raw = o.join "\n"
  end

  def subscribers
    self.subscribers_raw.split
  end

  def subscribers= s
    self.subscribers_raw = s.join "\n"
  end

  def delete_google_group
    Elilist.google_api.delete_group self.google_group_id
  end

  def google_group_add_member email
    Elilist.google_api.add_member_to_group email, self.google_group_id
  end

  def google_group_create
    Elilist.google_api.create_group self.google_group_id, [name, 'just a description', self.google_group_type]
  end

  def self.google_api
    adminuser = Plmt::Application.config.google_data_username
    password  = Plmt::Application.config.google_data_password
    @google_api ||= ProvisioningApi.new(adminuser, password)
  end

end

app/controllers/elilists_controller.rb
class ElilistsController < ApplicationController
  # POST /elilists
  def create
    list_params = params[:elilist]

    # transform owners array into newline separated flat string 
    list_params[:owners_raw] = list_params.delete(:owners_raw).reject!(&:empty?) * "\n" if list_params[:owners_raw]

    # subscribers_raw already is a flat string
    list_params[:subscribers_raw] = list_params.delete(:subscribers_raw).split.join "\n" if list_params[:subscribers_raw]

    @elilist = Elilist.new list_params

    respond_to do |format|
      if @elilist.save
        format.html { redirect_to @elilist, notice: 'Elilist was successfully created.' }
        format.json { render json: @elilist, status: :created, location: @elilist }
      else
        format.html { render action: "new" }
        format.json { render json: @elilist.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /elilists
  # GET /elilists.json
  def index
    @elilists = Elilist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elilists }
    end
  end

  # GET /elilists/1
  # GET /elilists/1.json
  def show
    @elilist = Elilist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @elilist }
    end
  end


=begin
  # GET /elilists/new
  # GET /panlists/id/migrate
  def new
    @panlist = Panlist.find_by_id params[:panlist_id]
    unless @panlist
      flash.alert = "Couldn't find panlist with id \"#{params[:panlist_id]}\""
      redirect_to '/dashboard/sy23' and return
    end
    @elilist = Elilist.new
    @elilist.owners = @panlist.owners
    @elilist.members = @panlist.members.join "\n"
    @elilist.name = @panlist.name

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @elilist }
    end
  end

  # GET /elilists/1/edit
  def edit
    @elilist = Elilist.find(params[:id])
  end

  # PUT /elilists/1
  # PUT /elilists/1.json
  def update
    @elilist = Elilist.find(params[:id])

    respond_to do |format|
      if @elilist.update_attributes(params[:elilist])
        format.html { redirect_to @elilist, notice: 'Elilist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @elilist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elilists/1
  # DELETE /elilists/1.json
  def destroy
    @elilist = Elilist.find(params[:id])
    @elilist.destroy

    respond_to do |format|
      format.html { redirect_to elilists_url }
      format.json { head :no_content }
    end
  end
=end
end

app/helpers/elilists_helper.rb
module ElilistsHelper
end

app/views/elilists/_form.html.erb
<div class="well">
  <%= simple_form_for @elilist, html: {class: 'form-horizontal'} do |f| %>
    <%= f.input :name, label: "Name (to be displayed)" %>
    <%= f.input :list_id, wrapper: :append, label: "EliList address" do %>
      <%= f.input_field :list_id %><span class="add-on">@elilists.yale.edu </span>
    <% end %>
    <%= f.input :description, as: :text, label: "A simple description of your list", input_html: {rows: 3} %>
    <%= f.input :owners_raw, collection: @elilist.owners, as: :check_boxes, label: 'List owners to migrate' %>
    <%= f.input :list_type, collection: %w[Moderated Announcement Discussion] %>
    <%= f.input :subscribers_raw, as: :text, label: "Email addresses of the members, one per line. (We automatically imported your existing members)", input_html: {rows: 30}   %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/elilists/edit.html.erb
<h1>Editing elilist</h1>

<%= render 'form' %>

<%= link_to 'Show', @elilist %> |
<%= link_to 'Back', elilists_path %>

app/views/elilists/index.html.erb
<h1>Listing elilists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Subscribers</th>
    <th>Owners</th>
    <th>List type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elilists.each do |elilist| %>
  <tr>
    <td><%= elilist.name %></td>
    <td><%= elilist.subscribers_raw %></td>
    <td><%= elilist.owners_raw %></td>
    <td><%= elilist.list_type %></td>
    <td><%= link_to 'Show', elilist %></td>
    <td><%= link_to 'Edit', edit_elilist_path(elilist) %></td>
    <td><%= link_to 'Destroy', elilist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Elilist', new_elilist_path %>

app/views/elilists/new.html.erb
<h1>Migrating list</h1>


<%= render 'form' %>


<%= link_to 'Back', elilists_path %>

app/views/elilists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @elilist.name %>
</p>

<p>
  <b>Subscribers:</b>
  <%= @elilist.subscribers_raw %>
</p>

<p>
  <b>Owners:</b>
  <%= @elilist.owners_raw %>
</p>

<p>
  <b>List type:</b>
  <%= @elilist.list_type %>
</p>


<%= link_to 'Edit', edit_elilist_path(@elilist) %> |
<%= link_to 'Back', elilists_path %>