config/routes.rb
Plmt::Application.routes.draw do
  resources :owners

  resources :elilists

  resources :panlists do
    member do
      get 'migrate' 
    end
  end

  root to: 'migrations#dashboard'
  match '/dashboard', to: 'migrations#dashboard'
  match '/dashboard/:netid', to: 'migrations#dashboard' 

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  attr_accessible :netid

  # has_and_belongs_to_many :panlists  
  # Virtually HABTM Panlists through the 'Ownership' model, which resides on Ahi
  
  def self.wrap netid
    Owner.find_or_initialize_by_netid netid
  end

  attr_accessor :panlists

  def panlists
    @panlists ||= Ownership.where(owner: self.netid).map { |oship| Panlist.find_by_list_id oship.panlist_id }
  end

  before_save :write_panlists
  def write_panlists
    # for each panlist, find or create an 
    @panlists.each { |p| Ownership.find_or_create_by_owner_and_list_id self.netid, p.list_id } if @panlists
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @owners }
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
    @owner = Owner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/new
  # GET /owners/new.json
  def new
    @owner = Owner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/1/edit
  def edit
    @owner = Owner.find(params[:id])
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(params[:owner])

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render json: @owner, status: :created, location: @owner }
      else
        format.html { render action: "new" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /owners/1
  # PUT /owners/1.json
  def update
    @owner = Owner.find(params[:id])

    respond_to do |format|
      if @owner.update_attributes(params[:owner])
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy

    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :netid %><br />
    <%= f.text_field :netid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <tr>
    <th>Netid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @owners.each do |owner| %>
  <tr>
    <td><%= owner.netid %></td>
    <td><%= link_to 'Show', owner %></td>
    <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
    <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Netid:</b>
  <%= @owner.netid %>
</p>


<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>