config/routes.rb
Plmt::Application.routes.draw do
  resources :owners

  resources :elilists

  resources :panlists do
    member do
      get 'migrate' 
    end
  end

  root to: 'migrations#dashboard'
  match '/dashboard', to: 'migrations#dashboard'
  match '/dashboard/:netid', to: 'migrations#dashboard' 

end

app/models/panlist.rb
require 'gappsprovisioning/provisioningapi.rb'

class Panlist < ActiveRecord::Base

  # Setup connection to legacy postgres database
  # establish_connection "ahi_#{Rails.env}"
  
  establish_connection "ahi_#{Rails.env}"
  self.table_name = 'lists'
  set_primary_key :list_id
  alias_attribute :name, :list_name
  alias_attribute :id, :list_id

  attr_accessor :owners

  attr_accessible :migrated, :name, :public, :subscribers
  has_and_belongs_to_many :owners

  # TODO(syu): modify to query LDAP / other service to return email addresses instead of netids
  def owners
    # set @owners instance variable by
    # 1) grabbing all Ownerships containing this panlist
    # 2) converting each Ownership into an Owner
    @owners ||= Ownership.where(list_id: self.id).map do |ownership|
      Owner.find_by_netid(ownership.owner_id)
    end
  end

  before_save :write_owners

  def write_owners
    # Note: we can't use owner_id and panlist_id because aliases aren't supported in dynamic find_or_creates
    @owners.each { |o| Ownership.find_or_create_by_owner_and_list_id o.netid, self.id } if @owners
  end

  def num_members 
    self.members.size
  end

  # TODO(syu): to be overriden with whatever function pulls in the flat list of subscriber addresses
  def members
    subscribers.split
  end
end

app/controllers/panlists_controller.rb
class PanlistsController < ApplicationController

  def show
    @panlist = Panlist.find_by_list_id params[:id]
    unless @panlist
      flash.alert = "Couldn't find panlist with id \"#{params[:id]}\""
      redirect_to '/dashboard' and return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @panlist }
    end
  end

  # The entry point for a panlist -> elilist migration
  # GET /panlists/1/migrate
  def migrate
    @panlist = Panlist.find_by_list_id params[:id]
    unless @panlist
      flash.alert = "Couldn't find panlist with id \"#{params[:id]}\""
      redirect_to '/dashboard/sy23' and return
    end
    @elilist = Elilist.new
    @elilist.owners = @panlist.owners.map &:netid
    @elilist.subscribers = @panlist.members
    @elilist.name = @panlist.name
    @elilist.list_id = @elilist.google_group_id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @elilist }
    end
  end

  # GET /panlists
  # GET /panlists.json
  def index
    @panlists = Panlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @panlists }
    end
  end

  # GET /panlists/new
  # GET /panlists/new.json
=begin
  def new
    @panlist = Panlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @panlist }
    end
  end

  # GET /panlists/1/edit
  def edit
    @panlist = Panlist.find(params[:id])
  end

  # POST /panlists
  # POST /panlists.json
  def create
    @panlist = Panlist.new(params[:panlist])

    respond_to do |format|
      if @panlist.save
        format.html { redirect_to @panlist, notice: 'Panlist was successfully created.' }
        format.json { render json: @panlist, status: :created, location: @panlist }
      else
        format.html { render action: "new" }
        format.json { render json: @panlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /panlists/1
  # PUT /panlists/1.json
  def update
    @panlist = Panlist.find(params[:id])

    respond_to do |format|
      if @panlist.update_attributes(params[:panlist])
        format.html { redirect_to @panlist, notice: 'Panlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @panlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /panlists/1
  # DELETE /panlists/1.json
  def destroy
    @panlist = Panlist.find(params[:id])
    @panlist.destroy

    respond_to do |format|
      format.html { redirect_to panlists_url }
      format.json { head :no_content }
    end
  end
=end
end

app/helpers/panlists_helper.rb
module PanlistsHelper
end

app/views/panlists/_form.html.erb
<%= form_for(@panlist) do |f| %>
  <% if @panlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@panlist.errors.count, "error") %> prohibited this panlist from being saved:</h2>

      <ul>
      <% @panlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subscribers %><br />
    <%= f.text_field :subscribers %>
  </div>
  <div class="field">
    <%= f.label :public %><br />
    <%= f.check_box :public %>
  </div>
  <div class="field">
    <%= f.label :migrated %><br />
    <%= f.check_box :migrated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/panlists/edit.html.erb
<h1>Editing panlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @panlist %> |
<%= link_to 'Back', panlists_path %>

app/views/panlists/index.html.erb
<h1>Listing panlists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Subscribers</th>
    <th>Public</th>
    <th>Migrated</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @panlists.each do |panlist| %>
  <tr>
    <td><%= panlist.name %></td>
    <td><%= panlist.subscribers %></td>
    <td><%= panlist.public %></td>
    <td><%= panlist.migrated %></td>
    <td><%= link_to 'Show', panlist %></td>
    <td><%= link_to 'Edit', edit_panlist_path(panlist) %></td>
    <td><%= link_to 'Destroy', panlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Panlist', new_panlist_path %>

app/views/panlists/migrate.html.erb
<h1>Migrating list</h1>


<%= render 'elilists/form' %>

app/views/panlists/new.html.erb
<h1>New panlist</h1>

<%= render 'form' %>

<%= link_to 'Back', panlists_path %>

app/views/panlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @panlist.name %>
</p>

<p>
  <b>Subscribers:</b>
  <%= @panlist.subscribers %>
</p>

<p>
  <b>Public:</b>
  <%= @panlist.public %>
</p>

<p>
  <b>Migrated:</b>
  <%= @panlist.migrated %>
</p>


<%= link_to 'Edit', edit_panlist_path(@panlist) %> |
<%= link_to 'Back', panlists_path %>